version: "3"

services:
    # Serviço Web
    user-nginx:
        image: nginx:1.13
        container_name: user-nginx
        volumes:
            - "${APP_PATH}:/var/www/html"
            - "${NGINX_PATH}:/etc/nginx/nginx.conf"
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - user-app

    # Serviço PHP
    user-app:
        build:
            context: ${PHP_PATH}
        container_name: user-app
        volumes:
            - "${APP_PATH}:/var/www/html"
        ports:
            - "${PHP_PORT}:9000"
        depends_on:
            - user-mysql
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASS=${MYSQL_PASS}

    # Serviço MySql
    user-mysql:
        image: mysql:5.7.20
        container_name: user-mysql
        volumes:
            - "db_data:/var/lib/mysql"
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
    default:
        external:
            name: cash_machine_simulator

volumes:
    db_data:
        driver: "local"